### ISSUE TITLE
ModuleNotFoundError: No module named 'guacamol_baselines'

### ISSUE THREAD

**Issue by martinkremnicky** [PaccMann/chemical_representation_learning_for_toxicity_prediction#15]
Hi, I can't see to get the Python API running, as it requires a module which I can't install for some reason.

**What I did:**
1. Installation:
```
git clone https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction.git
cd chemical_representation_learning_for_toxicity_prediction
conda env create -f conda.yml
conda activate toxsmi
pip install -e .
pip install gt4sd
```
2.  Then ran the code snippet from [README.md](https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction#python-api) 
```
from gt4sd.properties import PropertyPredictorRegistry
tox21 = PropertyPredictorRegistry.get_property_predictor('tox21', {'algorithm_version': 'v0'})
tox21('CCO')
```
and got an error at `from gt4sd.properties import PropertyPredictorRegistry` saying `ModuleNotFoundError: No module named 'guacamol_baselines'`

3. searched and found _a_ repo for [guacamol_baselines](https://github.com/GT4SD/guacamol_baselines) and tried to install via `pip install git+https://github.com/GT4SD/guacamol_baselines.git` and got `ERROR: Failed building wheel for guacamol-baselines` saying `error: [WinError 193] %1 is not a valid Win32 application`, but I cannot raise issues on that repo. It seems like a Windows 32-bit and 64 bit issue, but I'm not sure.

Do you know what I did wrong?
If not, do you happen to know of any other freely available model/ package that I could use to get molecule toxicity scores form SMILES?

Thanks!

Screenshots:

![image](https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction/assets/94135385/fddc92ae-51ab-4920-a3fc-b452e585833c)
![image](https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction/assets/94135385/1b1c252d-7d24-47db-b1a4-fd4df90e50dd)

![image](https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction/assets/94135385/5c3a433c-24e1-412f-8a6e-916f128c86f5)

**Comment by jannisborn** [comment]
Hi @martinkremnicky,

Thanks for the interest and opening the issue. If your final interest is to use the GT4SD property prediction submodule, why derailing the installation and starting from this repo?
What you're describing is not an issue of this repo, if at all it would belong to the GT4SD.
If you follow the installation instructions there, it should work. 
GT4SD is not fully pypi installable due to some source requirements which include guacamol_baselines.

**Comment by jannisborn** [comment]
Please use installation instructions from GT4SD and retry: 

https://github.com/GT4SD/gt4sd-core

**Comment by martinkremnicky** [comment]
Thanks, I will divert my further questions to GT4SD.
