### ISSUE TITLE
KeyErrors

### ISSUE THREAD

**Issue by aodecipher** [PaccMann/chemical_representation_learning_for_toxicity_prediction#16]
Hi!

When I tried to use the train_tox script, I got an error that is very similar to that in the following issue:
https://github.com/PaccMann/paccmann_predictor/issues/23

I tried to run the following:
python3 scripts/train_tox.py \
--train data/tox21_train.csv \
--test data/tox21_score.csv \
--smi data/tox21.smi \
--params params/mca.json \
--model toxsmi/models/Tox21/ \
--embedding data/smiles_vae_embeddings.pkl \
--finetune data/trained_models/Tox21/v0/weights/best_ROC-AUC_mca.pt \
--name t1

and I got this error:

Traceback (most recent call last):
  File "/content/crl/scripts/train_tox.py", line 285, in main
    model.load(finetune_path)
  File "/content/crl/toxsmi/models/mca.py", line 318, in load
    self.load_state_dict(weights)
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MCAMultiTask:
	size mismatch for smiles_embedding.weight: copying a param with shape torch.Size([222, 32]) from checkpoint, the shape in current model is torch.Size([222, 256]).
	size mismatch for convolutional_layers.convolutional_0.convolve.weight: copying a param with shape torch.Size([128, 1, 3, 32]) from checkpoint, the shape in current model is torch.Size([128, 1, 3, 256]).
	size mismatch for convolutional_layers.convolutional_1.convolve.weight: copying a param with shape torch.Size([128, 1, 5, 32]) from checkpoint, the shape in current model is torch.Size([128, 1, 5, 256]).
	size mismatch for convolutional_layers.convolutional_2.convolve.weight: copying a param with shape torch.Size([128, 1, 11, 32]) from checkpoint, the shape in current model is torch.Size([128, 1, 11, 256]).
	size mismatch for smiles_projections.smiles_projection_0.projection.weight: copying a param with shape torch.Size([256, 32]) from checkpoint, the shape in current model is torch.Size([256, 256]).
	size mismatch for smiles_projections.smiles_projection_1.projection.weight: copying a param with shape torch.Size([256, 32]) from checkpoint, the shape in current model is torch.Size([256, 256]).
	size mismatch for smiles_projections.smiles_projection_2.projection.weight: copying a param with shape torch.Size([256, 32]) from checkpoint, the shape in current model is torch.Size([256, 256]).
	size mismatch for smiles_projections.smiles_projection_3.projection.weight: copying a param with shape torch.Size([256, 32]) from checkpoint, the shape in current model is torch.Size([256, 256]).
	size mismatch for smiles_projections.smiles_projection_4.projection.weight: copying a param with shape torch.Size([256, 32]) from checkpoint, the shape in current model is torch.Size([256, 256]).
	size mismatch for smiles_projections.smiles_projection_5.projection.weight: copying a param with shape torch.Size([256, 32]) from checkpoint, the shape in current model is torch.Size([256, 256]).
	size mismatch for batch_norm.weight: copying a param with shape torch.Size([2496]) from checkpoint, the shape in current model is torch.Size([3840]).
	size mismatch for batch_norm.bias: copying a param with shape torch.Size([2496]) from checkpoint, the shape in current model is torch.Size([3840]).
	size mismatch for batch_norm.running_mean: copying a param with shape torch.Size([2496]) from checkpoint, the shape in current model is torch.Size([3840]).
	size mismatch for batch_norm.running_var: copying a param with shape torch.Size([2496]) from checkpoint, the shape in current model is torch.Size([3840]).
	size mismatch for dense_layers.dense_0.projection.weight: copying a param with shape torch.Size([1024, 2496]) from checkpoint, the shape in current model is torch.Size([1024, 3840]).
	size mismatch for final_dense.ensemble.0.weight: copying a param with shape torch.Size([12, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for final_dense.ensemble.0.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for final_dense.ensemble.1.weight: copying a param with shape torch.Size([12, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for final_dense.ensemble.1.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for final_dense.ensemble.2.weight: copying a param with shape torch.Size([12, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for final_dense.ensemble.2.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for final_dense.ensemble.3.weight: copying a param with shape torch.Size([12, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for final_dense.ensemble.3.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for final_dense.ensemble.4.weight: copying a param with shape torch.Size([12, 512]) from checkpoint, the shape in current model is torch.Size([1, 512]).
	size mismatch for final_dense.ensemble.4.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([1]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/crl/scripts/train_tox.py", line 399, in <module>
    main(
  File "/content/crl/scripts/train_tox.py", line 288, in main
    raise KeyError(f"Could not restore model from {finetune_path}")
KeyError: 'Could not restore model from data/trained_models/Tox21/v0/weights/best_ROC-AUC_mca.pt'

Thank you in advance!

**Comment by jannisborn** [comment]
Hi,
Thanks for the interest in our work. It seems you are restoring from a checkpoint but then you are passing an exemplary config file from `--params params/mca.json`.

Have you tried passing the config file inside `data/trained_models/Tox21/v0/`?

**Comment by aodecipher** [comment]
Thank you so much for the prompt response.
Yes, that's a silly mistake. I've modified the command to the following

python3 scripts/train_tox.py \
--train data/tox21_train.csv \
--test data/tox21_score.csv \
--smi data/tox21.smi \
--params data/trained_models/Tox21/v0/model_params.json \
--model toxsmi/models/Tox21/ \
--embedding data/smiles_vae_embeddings.pkl \
--finetune data/trained_models/Tox21/v0/weights/best_ROC-AUC_mca.pt \
--name t2

but I still get an error:

Traceback (most recent call last):
  File "scripts/train_tox.py", line 407, in <module>
    args.finetune,
  File "scripts/train_tox.py", line 163, in main
    label_columns = params.get("label_columns", list(range(params["num_tasks"])))
KeyError: 'num_tasks'

**Comment by aodecipher** [comment]
Also, I assume your code doesn't require GPUs (they can run on CPU-only devices), correct?

**Comment by jannisborn** [comment]
It's a multitask model and "num_tasks" defines the number of nodes in the output layer -- which you have to set. With the Tox21 I model, it should be 12

**Comment by aodecipher** [comment]
Ok, first good news:
This command is working:
python3 scripts/train_tox.py \
--train data/tox21_train.csv \
--test data/tox21_score.csv \
--smi data/tox21.smi \
--params data/trained_models/ClinTox/v0/model_params.json \
--model toxsmi/models/ClinTox/ \
--name t1

I found that the model_params.json under Sider and Clintox folders both contain the num_tasks, it was just the one under Tox21 that's missing.

Now the not-so-good news;
after adding num_tasks in the 'data/trained_models/Tox21/v0/model_params.json', I got the following error again when running the command in my previous message:
KeyError(f"Could not restore model from {finetune_path}")

When when I ran the corresponding version for Clintox, I also get this error
python3 scripts/train_tox.py \
--train data/tox21_train.csv \
--test data/tox21_score.csv \
--smi data/tox21.smi \
--params data/trained_models/ClinTox/v0/model_params.json \
--model toxsmi/models/ClinTox/ \
--embedding data/smiles_vae_embeddings.pkl \
--finetune data/trained_models/ClinTox/v0/weights/best_ROC-AUC_mca.pt \
--name t3

Number of parameters 3844042
Traceback (most recent call last):
  File "scripts/train_tox.py", line 285, in main
    model.load(finetune_path)
  File "/home/ao/Apps/crl/toxsmi/models/mca.py", line 317, in load
    weights = torch.load(path, *args, **kwargs)
  File "/home/ao/miniconda3/envs/toxsmi/lib/python3.7/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ao/miniconda3/envs/toxsmi/lib/python3.7/site-packages/torch/serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "/home/ao/miniconda3/envs/toxsmi/lib/python3.7/site-packages/torch/serialization.py", line 958, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "/home/ao/miniconda3/envs/toxsmi/lib/python3.7/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/ao/miniconda3/envs/toxsmi/lib/python3.7/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/ao/miniconda3/envs/toxsmi/lib/python3.7/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/train_tox.py", line 407, in <module>
    args.finetune,
  File "scripts/train_tox.py", line 288, in main
    raise KeyError(f"Could not restore model from {finetune_path}")
KeyError: 'Could not restore model from data/trained_models/ClinTox/v0/weights/best_ROC-AUC_mca.pt'

This is ran on a CPU-only computer, so i assume the CUDA error should be ignored.

**Comment by aodecipher** [comment]
Also, after training the ClinTox mode, I used the eval script as the following:
python3 scripts/eval_tox.py \
-model toxsmi/models/ClinTox/t1 \
-smi data/tox21.smi \
-labels data/tox21_test.csv \
-checkpoint best_ROC-AUC

but i got this error:
Evaluation about to start...

100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.10it/s]
Shape of attention scores (296, 24, 273).
Traceback (most recent call last):
  File "scripts/eval_tox.py", line 298, in <module>
    args.threshold_binarization,
  File "scripts/eval_tox.py", line 272, in main
    result = performer.inference_report(labels, predictions)
  File "/home/ao/Apps/crl/toxsmi/utils/performance.py", line 239, in inference_report_binary_classification
    negative_precision = report["0"]["precision"]
KeyError: '0'

**Comment by jannisborn** [comment]
> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

--> Seems that loading weights from a pretrained model currently assumes the device to be identical to the training device. Training device was GPU, finetuning device is CPU here, hence you have to adapt the code using `map_location` as suggested in the error message. Feel free to submit a PR!

Regarding the KeyError, I have seen this also before, try replacing "0" with "0.0"

**Comment by jannisborn** [comment]
I pushed a fix for both [6887c80](https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction/commit/6887c8067c695f50f9f6c2edbd127b88f4333711)
