### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by youweiliang** [PaccMann/chemical_representation_learning_for_toxicity_prediction#17]
Hi, thanks for the great work. Is the dataset released? Under that `data` folder, I could not find any csv data files, but only readme files.

**Comment by jannisborn** [comment]
Hi @youweiliang,

Thanks for the interest in our work. Indeed, we released pretrained models that can be used either through a 3-line python API or via a gradio webapp.

For data availability please refer to the [paper](https://pubs.rsc.org/en/content/articlehtml/2023/dd/d2dd00099g). We do not see a value in re-distributing data that is already publicly available. Rather, the original data creators and data releasers should be credited for that. Here's the statement from the paper:

_The data from the original Tox21 challenge is available from Huang R. et al.:[90](https://pubs.rsc.org/en/content/articlehtml/2023/dd/d2dd00099g#cit90)https://tripod.nih.gov/tox21/challenge/. The data from the MoleculeNet benchmark is available from Wu Z. et al.:[11](https://pubs.rsc.org/en/content/articlehtml/2023/dd/d2dd00099g#cit11)https://moleculenet.org/datasets. The data from the cytotoxicity case study is available from the FMP authors.[17,92](https://pubs.rsc.org/en/content/articlehtml/2023/dd/d2dd00099g#cit17)_

Hope this helps!
