### ISSUE TITLE
the number of the augmentation

### ISSUE THREAD

**Issue by feiyang-cai** [PaccMann/chemical_representation_learning_for_toxicity_prediction#18]
Hi,

Thanks for your nice work.

Is it possible to provide the number of augmentations for each molecule you did in your experiment? I didn't see this information in the paper, but maybe I didn't notice that.

Thanks!

**Comment by jannisborn** [comment]
Hi 
Thanks for the interest in our work. We used smiles augmentation as implemented in pytoda package. It’s online augmentation similar to rotations in an image so there’s not a fixed number per molecule.

**Comment by jannisborn** [comment]
Check the Supplementary Materials for details: https://www.rsc.org/suppdata/d2/dd/d2dd00099g/d2dd00099g1.pdf


<img width="717" alt="image" src="https://github.com/PaccMann/chemical_representation_learning_for_toxicity_prediction/assets/15703818/32df05f6-0eaf-4fc5-ae80-232b47618265">

**Comment by feiyang-cai** [comment]
Really appreciate your info. 

Thanks!
